### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by rita-s** [rita-s/SoC-onboarding#1]
### Subtasks
- [x] Create GitHub repository
- [x] Clone repository locally
- [x] Set up GitHub Project board
- [x] Create initial HTML file
- [x] Create initial CSS file
- [x] Create initial JS file
