### ISSUE TITLE
Divide design into sections

### ISSUE THREAD

**Issue by rita-s** [rita-s/SoC-onboarding#2]
### Subtasks
- [x] Section 1: Search bar
- [x] Section 2: Top-Icon-Slider
- [x] Section 3: Experiences
- [x] Section 4: Past Experiences
- [x] Section 5: Support
- [x] Section 6: Hosting
- [x] Section 7: Airbnb
- [x] Section 8: Footer
- [x] Section 9: Fixed icons
