### ISSUE TITLE
Decide which sections will be in separate branches

### ISSUE THREAD

**Issue by rita-s** [rita-s/SoC-onboarding#4]
### Subtasks
- [ ] Branch 1: Search
- [ ] Branch 2: Icons (Top-Icon-Slider + Fixed icons)
- [ ] Branch 3: Experiences (Experiences + Past Experiences)
- [ ] Branch 4: Links (Support + Hosting + Airbnb + Footer)
